# Generated by Django 3.1.3 on 2020-11-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0003_auto_20201113_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='title',
            field=models.CharField(blank=True, default='Title', max_length=100),
        ),
    ]
